package com.hz1202.dao;

import com.hz1202.model.SysDept;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    int insertSelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    SysDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDept record);

    /**
     * 获取全部部门
     */
    List<SysDept> getAll();

    /**
     * 根据level获取下级部门
     */
    List<SysDept> getChildDeptListByLevel(@Param("level")String level);

    /**
     * 批量更新部门
     */
    void bachUpdateDept(@Param("deptList") List<SysDept> deptList);
    /**
     * 查询数据是否存在
     */
    int countByNameAndParentId(@Param("parentId")Integer parentId,@Param("name") String name, @Param("id")Integer id);
}