package com.hz1202.dao;

import com.hz1202.model.SysUserAcl;

public interface SysUserAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    int insert(SysUserAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    int insertSelective(SysUserAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    SysUserAcl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_acl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserAcl record);
}